### ISSUE TITLE
Make terra classic data visualization more accessible for beginners

### ISSUE THREAD

**Issue by GuillaumeFerreira** [geoffmunn/terra.py#3]
Interacting with Terra Classic using Python can be challenging. Therefore, I am considering creating examples using FastAPI or NiceGUI. This will provide a variety of examples to make the documentation more user-friendly and comprehensive.

**Comment by geoffmunn** [comment]
If you have any examples, I can replace the old documentation with your contributions.

**Comment by GuillaumeFerreira** [comment]
In the next few days, I will make an attempt to write all of this
