### ISSUE TITLE
Create a connection fronted wallet Terra Classic

### ISSUE THREAD

**Issue by GuillaumeFerreira** [geoffmunn/terra.py#4]
How to establish a connection between a Terra Classic wallet and a Django-based Python application?
I'm having trouble finding a JavaScript base to integrate into Django.

**Comment by GuillaumeFerreira** [comment]
The concept involves developing a Python API that establishes communication between a JavaScript app (based on React) with the wallet provider

The Terra Station is connected to a JavaScript frontend app, which, in turn, communicates with a Python API

**Comment by geoffmunn** [comment]
If I understand this correctly, you want to create a python wallet but connect to it via JavaScript?
Would something like http://pyjs.org/ work?

Otherwise I think it would be risky - anything that needs to expose the seed phrase is a massive security risk, and the Python objects would be incompatible with JavaScript (I think).

**Comment by GuillaumeFerreira** [comment]
I'm looking to create a simple connection to Terra Station, but I'm not sure how to best describe what I mean. Perhaps a comparison to a[ wallet provider](https://github.com/terra-money/wallet-provider) would be helpful.

**Comment by geoffmunn** [comment]
Terra Station is just a GUI around the basic functionality. The terra.js and terra.py libraries provide exactly the same functionality (more or less) so depending on what you need to do, the terra.py library might be useful for Django.

The only things I haven't got going yet are:

- governance voting
- contract creation

Everything else should work.

**Comment by geoffmunn** [comment]
If you have a precise problem you want an example for, let me know :)

**Comment by GuillaumeFerreira** [comment]
I would like to make a django application that can connect to Terra Station, but I don't see how to connect my front end to Terra Station

**Comment by geoffmunn** [comment]
Terra Station is written in Typescript and doesn't have an API, but even if it did I don't think this is the correct approach.

If you want to expose values or functionality that you can find inside Terra Station, then the terra.py project can definitely do that - no need for Terra Station.

If you give me an example of what you want to display, I can outline how it would work with terra.py

**Comment by GuillaumeFerreira** [comment]
I just want to make a web application with Django that can connect to a wallet like Terra Station, so that users can see information related to their activity on the Terra Classic blockchain.

With a button like this
![Capture](https://github.com/geoffmunn/terra.py/assets/17759686/e5e21b0e-0294-4794-98ee-39d42a25dcc9)

**Comment by geoffmunn** [comment]
Ahh I see.

Have you tried something like this?
https://ahmedyasin487.medium.com/how-to-add-walletconnect-with-django-399bec058566

If this works, then depending on what methods it exposes we can then access the wallet.

**Comment by GuillaumeFerreira** [comment]
I finally succeeded with a react typescript frontend

**Comment by geoffmunn** [comment]
The next version of this project is going to be awesome - it supports workflows which are super userful if you're interested.

**Comment by GuillaumeFerreira** [comment]
Yes, I am interested. If you need assistance for the next version, I am more than willing to help you
