### ISSUE TITLE
 json listing the most important tokens

### ISSUE THREAD

**Issue by GuillaumeFerreira** [geoffmunn/terra.py#9]
There is currently a method via the Terra Classic SDK to list the tokens, but I think it would be more efficient to create a JSON file that lists the public keys of the most important tokens. This would save time when creating databases for future applications.

This may be a misconception, but i propose the idea.

**Comment by geoffmunn** [comment]
There is always a tricky balance between hardcoding a token list and using a dynamic list. Dynamically building it each time will mean that we always have the correct details.
Hardcoding it will mean that any changes to the tokens will require the entire project to be updated by all users.

Just so I can check, what method are you referring to?

**Comment by GuillaumeFerreira** [comment]
it seems to me that there is something in API to list the coins of terra classic , but I confess I don't know exactly

terra_classic_sdk/client/lcd/api

**Comment by geoffmunn** [comment]
This endpoint lists all the coins:
https://lcd.terrarebels.net/terra/oracle/v1beta1/denoms/actives

The problem though is that you need to do a manual conversion to the readable name or infer it from the token name.

The endpoint is quick to respond and the returned data is small so I'm not sure if there's much of a time saving to be had here.

**Comment by GuillaumeFerreira** [comment]
I am looking for a more detailed JSON format with more information about the token.
{
  "adresse": "terra1lx6w28yvma0y8hll0svg687ft694yrgax5k276",
  "decimals": 6,
  "name": "Terraport",
  "symbol": "TERRA",
   "logo": { "url": "https://i.ibb.co/GtmvHT4/logo.png"}
}
Information on [finder terrarebel](https://finder.terrarebels.net/mainnet/address/terra1lx6w28yvma0y8hll0svg687ft694yrgax5k276)

In order to be able to easily create drop-down lists or other utilities for a web application.

**Comment by GuillaumeFerreira** [comment]
This endpoint list all of token supply ? How to reach other pages ?
[https://lcd.terrarebels.net/cosmos/bank/v1beta1/supply](https://lcd.terrarebels.net/cosmos/bank/v1beta1/supply)

total = 191 , but 100 tokens in this page.
![image](https://github.com/geoffmunn/terra.py/assets/17759686/73ac39ae-6b9e-405a-9970-bd443885947b)

**Comment by geoffmunn** [comment]
Yes, you need to do an API request and provide a pagination reference. It's not hard, but it is a bit annoying.
Also, all the IBC coins need a denom lookup which is yet another step - hard-coding it is definitely preferable if you are only interested in a few main coins.
I really struggled to find a method to get the human-readable name and details of any random coin. I ended up hard-coding a list with everything I needed on the assumption that it won't change much.

**Comment by GuillaumeFerreira** [comment]
I've finally managed to list all the tokens in the api at once, I don't know if that was my original idea but I think I can close this issue.

```
    from terra_classic_sdk.client.lcd import LCDClient
    from terra_classic_sdk.client.lcd.params import PaginationOptions
    TERRA = LCDClient(chain_id="columbus-5", url="https://terra-classic-lcd.publicnode.com")
    
    total_supply = TERRA.bank.total()
    
    pagOpt = PaginationOptions(limit=total_supply[1]['total'], count_total=True)
    
    total_supply_denom = TERRA.bank.total(params=pagOpt)
    
    for coin in total_supply_denom[0]:
        print("Supply: {} , Denom: {}".format(coin.amount,coin.denom))
```

![image](https://github.com/geoffmunn/terra.py/assets/17759686/32c2edd2-bebe-4593-abfb-663b0a56672e)

**Comment by geoffmunn** [comment]
If you want the human-readable versions of the ibc tokens, then use this:


```
    from terra_classic_sdk.client.lcd import LCDClient
    from terra_classic_sdk.client.lcd.params import PaginationOptions
    from classes.wallet import UserWallet
    TERRA = LCDClient(chain_id="columbus-5", url="https://terra-classic-lcd.publicnode.com")

    total_supply = TERRA.bank.total()

    pagOpt = PaginationOptions(limit=total_supply[1]['total'], count_total=True)

    total_supply_denom = TERRA.bank.total(params=pagOpt)

    wallet:UserWallet = UserWallet().create(denom = 'uluna')
    for coin in total_supply_denom[0]:
        denom:str = wallet.denomTrace(coin.denom)
        print("Supply: {} , Denom: {}".format(coin.amount, denom))
```
